csrutil authenticated-root disable;
diskutil mount /Volumes/diskMacOs;
 Mount -uv /Volumes/diskMacOs;	
 cd /Volumes/diskMacOs/System/Library/LaunchAgents;
mkdir tmp;
mv com.apple.ManagedClientAgent.* tmp/;
mv com.apple.mdmclient.* tmp/;
cd ../LaunchDaemons;
mkdir tmp;
mv com.apple.ManagedClient.* tmp/;
mv com.apple.mdmclient.* tmp/;
bless --folder /Volumes/diskMacOs/System/Library/CoreServices --bootefi --create-snapshot;
