csrutil authenticated-root disable;
diskutil mount /Volumes/tuthvn;
 Mount -uv /Volumes/tuthvn;	
 cd /Volumes/tuthvn/System/Library/LaunchAgents;
mkdir tmp;
mv com.apple.ManagedClientAgent.* tmp/;
mv com.apple.mdmclient.* tmp/;
cd ../LaunchDaemons;
mkdir tmp;
mv com.apple.ManagedClient.* tmp/;
mv com.apple.mdmclient.* tmp/;
bless --folder /Volumes/tuthvn/System/Library/CoreServices --bootefi --create-snapshot;
